name: Build and Upload Artifacts
on:
  push:
    branches: [ main ]

jobs:
  build-and-upload:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Build Server
        run: |
          go build -o server.exe
          echo "Server built successfully!"
      
      - name: Build Client
        run: |
          cd client/python
          python -m pip install -r requirements.txt
          pyinstaller --onefile main.py
          echo "Client built successfully!"
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: server-and-client
          path: |
            ./server.exe
            ./client/python/dist/main.exe
